---
- hosts: centos6
  remote_user: ansible
  become: yes

  vars:
    - packages: "ntp, ntpdate"
    
  tasks:
    - name: install packages
      yum:
        name: "{{packages}}"
        state: latest

    - name: configure ntp
      template:
        src: /home/ansible/ansible/template/ntp_client6.conf
        dest: /etc/ntp.conf

    - name: start ntp
      service:
        name: ntpd
        enabled: yes
        state: started

 #   - name: open firewall port
 #     firewalld:
 #       service: ntp
 #       immediate: true
 #       permanent: true
 #       state: enabled
