---
- hosts: ftp_repo
  remote_user: ansible
  become: yes

  vars:
    - packages: "dhcp, tftp, tftp-server, syslinux, vsftpd, xinetd"

  tasks:
    - name: install packages
      yum:
        name: "{{packages}}"
        state: 'present'
        update_cache: 'yes'

    - name: template for dhcp
      template:
        src: /home/ansible/ansible/template/dhcpd.conf
        dest: /etc/dhcp/dhcpd.conf

    - name: template for tftp
      template:
        src: /home/ansible/ansible/template/tftp.j2
        dest: /etc/xinetd.d/tftp

    - name: copy files to tftpboot
      copy:
        src: /usr/share/syslinux/pxelinux.0
        dest: /var/lib/tftpboot/
        owner: root
        group: root
        mode: 0644
        remote_src: true

    - name: copy files to tftpboot
      copy:
        src: /usr/share/syslinux/menu.c32
        dest: /var/lib/tftpboot/
        owner: root
        group: root
        mode: 0644
        remote_src: true

    - name: copy files to tftpboot
      copy:
        src: /usr/share/syslinux/memdisk
        dest: /var/lib/tftpboot/
        owner: root
        group: root
        mode: 0644
        remote_src: true

    - name: copy files to tftpboot
      copy:
        src: /usr/share/syslinux/mboot.c32
        dest: /var/lib/tftpboot/
        owner: root
        group: root
        mode: 0644
        remote_src: true

    - name: copy files to tftpboot
      copy:
        src: /usr/share/syslinux/chain.c32
        dest: /var/lib/tftpboot/
        owner: root
        group: root
        mode: 0644
        remote_src: true

    - name: create directories
      file:
        path: /var/lib/tftpboot/pxelinux.cfg
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: create directories
      file:
        path: /var/lib/tftpboot/networkboot
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: create directories
      file:
        path: /var/lib/tftpboot/networkboot/centos7
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: create directories
      file:
        path: /var/lib/tftpboot/networkboot/centos6
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: copy files
      copy:
        src: /var/ftp/pub/repo/images/pxeboot/vmlinuz
        dest: /var/lib/tftpboot/networkboot/centos7
        remote_src: true

    - name: copy files
      copy:
        src: /var/ftp/pub/repo/images/pxeboot/initrd.img
        dest: /var/lib/tftpboot/networkboot/centos7
        remote_src: true

    - name: template for centos7
      template:
        src: /home/ansible/ansible/template/centos7.cfg
        dest: /var/ftp/pub

    - name: template default
      template:
        src: /home/ansible/ansible/template/default.j2
        dest: /var/lib/tftpboot/pxelinux.cfg/default

    - name: start and enable services
      service:
        name: xinetd
        enabled: yes
        state: started

    - name: start and enable services
      service:
        name: dhcpd
        enabled: yes
        state: started

    - name: start and enable services
      service:
        name: vsftpd
        enabled: yes
        state: started
