---
- hosts: slave176
  remote_user: ansible
  become: yes
  become_method: sudo

  tasks:

    - name: install bind
      yum:
        name: bind*
        state: latest

    - name: template config file
      template:
        src: /home/ansible/ansible/template/slave176.conf
        dest: /etc/named.conf
        owner: root
        group: named
        mode: '0640'

    - name: enable and start named
      service:
        name: named
        enabled: yes
        state: started

    #- name: open firewall port
    #  firewalld:
    #    service: dns
    #    immediate: true
    #    permanent: true
    #    state: enabled
